language: java
dist: bionic
sudo: false
git:
  depth: false
cache:
  directories:
  - $HOME/.m2
addons:
  sonarcloud:
    organization: "svenpeldszus-github"
    token:
        secure: ${SONAR_TOKEN}
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -fae -Dsonar.projectKey=SvenPeldszus_emoflon-tgg-mutation-test-tool
